{
 "title": "PID Controller - Oven Demo",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "controller",
    "label": "Demo",
    "query": {
     "query": "label_values(oven_temperature,controller)"
    }
   },
   { "name": "name", "label": "PID", "query": { "query": "label_values(pid_current,name)" } }
  ]
 },
 "panels": [
  { "title": "Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Oven Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "sum by (controller) (oven_temperature{\n    controller=~\"$controller\",\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Oven Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (controller) (oven_power_ratio{\n    controller=~\"$controller\",\n})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PID: $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "name" },
  {
   "title": "Error = Target - Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "expr": "pid_current{\n  name=\"$name\",\n} - pid_target{\n  name=\"$name\",\n}",
     "legendFormat": "Error = Target - Current"
    }
   ]
  },
  {
   "title": "Control Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "pid_control_signal{\n  name=\"$name\",\n}",
     "legendFormat": "Control Signal"
    }
   ]
  },
  {
   "title": "P, I and D Gain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "pid_gain{name=\"$name\"}",
     "legendFormat": "{{term}}"
    }
   ]
  },
  {
   "title": "P, I and D Term",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "pid_term{name=\"$name\"}",
     "legendFormat": "{{term}}"
    }
   ]
  }
 ]
}