version: "2"
linters:
  enable:
    - bodyclose
    - revive
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
